language: node_js

node_js:
  - "7"
  - "6"
  - "4"

script:
  - gulp ci
  - gulp zip

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key:
    secure: RUN7W3/VCwuHZmqBg8QXbDjhk5dwNMlLqGGJr2MNbVJemt1WlyQeFytpLdm5uGIRxZ569u7rxxvv5FAu7nSq+W2X3ygyw5fL19uR3tZQezIpEEHie4AaAY8Ujp1GzEbF7mF6+vjtA2fBQgYMB7WLWr2PLPgVqRcdNEWztWpcZzsukKOLMa/PgEzu+nbvtXpSycEKlom2iDFm7usBwneu08KD5kNefOu0xW8sPHUxBe5oRgJirPtLwfvvWJiZ1woyUQATfuEvoHDtft2ajU6rrJhZ1L0Y5yzfQgEClTQu7FPhetOo8WctJLX3jpkGF7/iVpPHQRV/QyJKNksBxCiAqHQDRH9WJQyU6/EzjqT5cj0oR5WnqrYi4IP8+DMU7XrzAHbvKh3dyjknVlYOfZtO/bLAyitA2eJEbmHwKttVV1tpU80C/E3uILYdOk2v7XOsbtYSMqLSKKwWXRmgGMYJcqGlkCNz4QAN/jpPb11w+CAUEFrTnqXjbEZ0ry4P2jYrXkruleDpcibncdm2XlvmVp/warvhBXvdPNTd2U8TJ29KO0QiV+VlyqSGqZ4gO1aEg2Hs2pzFdJBrcMjwjhzcS29JkjNHmGDWO0t4apQ3zdpxZOlAjUVEdueUGdJ3lhkwZ0JbTpbywLHfVGlBWc2m1nNVa4wYTdklgc1B+B5Kh58=
  skip_cleanup: true
  file: firebase-sensor.zip
  on:
    tags: true
    repo: seblucas/firebase-sensor
    node: '6'
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
    tags: true
    node: '6'
  token:
    secure: gJda4V1tUfESMX1Lqh6qzpFCvoL0Y9WAy7IshiaA5bLejr5YiYqC7ulEzFbBaTX+fe/vnmLd1H6M2PWyFUzVnEaNZ+VOZpq5b+4R+33YGq2JYfvFkWHOBelfE/U57g5iKb5McygQFFZk9d87niLMQaKqp0G8V0E94OMzGeN4Y5Zv/pl2K+lF3rHNQkQStmqJH3/Dc8pfnkROAuC3ngs7v8nUc2gJxnsEdsYXKRxsIio+zS2wwsOsur4vlEiD/lARMFIBTjmM/s+w4KMZp5BtovUGyyk52szmNz/JTjWqYav4covUI/XxB91q1fcUNQYHPi8hsUkQjgqeR4PSL9p0iEyYkwMFk3w5QDRVU2YTNVbArYQntg3sgddM9LSW8fBXWyMFktL+rMBMNMcJKCN19s5vMgwJm6tyifzvThK1z8zoK7yc58SywzX87VgroY9zDHNTiVe1EkeF3+5c7cuilxyN1AkcaCMr22xpklyuqgB9Xqt1dQmHLsfMOov8kF70c8o0KDTrECDCjVhCGdqg6DGwG8t/Ta4zv0K+cAIhi+UmV6raDk1JljoCiXuAX16v/yzz263YV9LyX9/OveDN7Y74eCNRFYUmpFcAhPxkjMNyM8nHAOi3cIMwv9u1ZSzjV1ydfFeDXIcOqSRriX5oJvk0f33v2UHidJ24UfRMPkc=
